version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "eventBridgePocApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1pw4q9vk7rodm"
s3_prefix = "eventBridgePocApp"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

